INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE)
VALUES ('root', 'Nonamed Company', '');

INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE)
VALUES ('d0001','경영지원', 'root');

INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE)
VALUES ('d0002','개발본부', 'root');

INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE)
VALUES ('d0003','개발1팀', 'd0002');

INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE)
VALUES ('d0004','개발2팀', 'd0002');

INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE)
VALUES ('d0005','개발3팀', 'd0002');

INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE)
VALUES ('d0006','운영본부', 'root');
