INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE, DEPTH)
VALUES ('root', 'Nonamed Company', '', '0');

INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE, DEPTH)
VALUES ('d0001','경영지원', 'root', '1');

INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE, DEPTH)
VALUES ('d0002','개발본부', 'root', '1');

INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE, DEPTH)
VALUES ('d0003','개발1팀', 'd0002', '2');

INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE, DEPTH)
VALUES ('d0004','개발2팀', 'd0002', '2');

INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE, DEPTH)
VALUES ('d0005','개발3팀', 'd0002', '2');

INSERT INTO DEPARTMENT (DEPT_CODE, DEPT_NAME, UP_DEPT_CODE, DEPTH)
VALUES ('d0006','운영본부', 'root', '1');
