CREATE TABLE USER (
  NO int(11) NOT NULL DEFAULT 0,
  NAME varchar(100) DEFAULT NULL,
  EMAIL varchar(100) DEFAULT NULL,
  DEPT_CODE varchar(100) DEFAULT NULL,
  PRIMARY KEY (NO)
);

CREATE TABLE DEPARTMENT (
  DEPT_CODE varchar(255) NOT NULL,
  DEPT_NAME varchar(255) DEFAULT NULL,
  UP_DEPT_CODE varchar(255) DEFAULT NULL,
  PRIMARY KEY (DEPT_CODE)
);